/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from "@react-three/drei";


export function Model() {
  const { nodes, materials } = useGLTF("/models/PizzaOptimizada2.glb");
  return (
    <group dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pizza.geometry}
        material={materials.pizza}
        scale={0.025}
      />
    </group>
  );
}

useGLTF.preload("/PizzaOptimizada2.glb");